name: Release on main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release-on-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Compile (Windows)
        id: compile-windows
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-windows.outputs.BUILT_CHECKSUM }}

      - name: Compile (Linux)
        id: compile-linux
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_CHECKSUM }}

      - name: Compile (macOS)
        id: compile-macos
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: x86_64-apple-darwin
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-macos.outputs.BUILT_CHECKSUM }}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automated build"
          files: |
            ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-windows.outputs.BUILT_CHECKSUM }}
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_CHECKSUM }}
            ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-macos.outputs.BUILT_CHECKSUM }}